name: Deploy Backend to Fly.io

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Make sure the app exists (create if missing) and target London (lhr)
      - name: Ensure Fly app exists
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          set -e
          # Show auth and apps for visibility
          flyctl auth token >/dev/null
          flyctl apps list || true
          # Create app if it doesn't exist
          if ! flyctl apps show trash-tracker-api >/dev/null 2>&1; then
            flyctl apps create trash-tracker-api
          fi

      # Deploy using our Dockerfile and explicit region
      - name: Deploy using Fly (Dockerfile, remote builder)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          set -e
          flyctl deploy --app trash-tracker-api --region lhr --remote-only --verbose
